# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    configs:
        main_config: 
            toolbar: standard

    # toolbars:
    #     configs:
    #         my_toolbar_1: [ "@document"]
    #     items:
    #         document: [ "Bold", "Underline", "Font", "Cut", "Paste" ]
